### ISSUE TITLE
Anti-Baritone plugin easily blocks Baritone and kicks the player in seconds

### ISSUE THREAD

**Issue by VirxEC** [cabaletta/baritone#895]
## Describe your suggestion
Download the anti-cheat plugin called Matrix from https://www.spigotmc.org/resources/matrix-anticheat-hack-killaura-blocker-machine-learning-1-8-1-12-1-13-1-14.64635/, and boot up a server with it. Open Minecraft with Baritone. Personally, I just did #mine oak_log, and the plugin kicked me in seconds with the default settings for Baritone.

## Settings
Add a legit setting to Baritone where the head moves slower, blocks are placed slower, and everything overall just looks legit to the point where a human can't tell. It might be slower, but that's why it's an option. Also, it should be slower because humans are just slower than computers in general.

## Context
This might make Baritone a bit slower, but also undetectable.

## Final checklist
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by LoganDark** [comment]
I can start development on this after I'm done with the new commands

**Comment by VirxEC** [comment]
Seriously? Awesome!

**Comment by zbot473** [comment]
Does it kick you while walking, or just when moving the head?

**Comment by VirxEC** [comment]
When placing and breaking blocks. Not while moving because I turned free look off.

**Comment by LoganDark** [comment]
@VirxEC freelook is client-side

**Comment by leijurv** [comment]
What version of Minecraft?

**Comment by VirxEC** [comment]
Only tested in 1.14.4, but the plugin supports 1.8.X and 1.12-1.14.4

**Comment by VirxEC** [comment]
Btw it uses machine learning, so... it better be a very human bot.

**Comment by LoganDark** [comment]
@VirxEC it uses ML for killaura detection but nothing else

**Comment by VirxEC** [comment]
No, they train the anti-cheat with machine learning enabled on everything to develop it, then they package it with the data. Here's my server's machine-learning.yml file: https://pastebin.com/PBRRPXLt

**Comment by 0-x-2-2** [comment]
> Btw it uses machine learning, so... it better be a very human bot.

"""machine learning"""

**Comment by LoganDark** [comment]
> Btw it uses machine learning, so... it better be a very human bot.

That can go both ways:
- It adjusts itself if you look too much like a bot, OR
- It adjusts itself to not detect bots if you make it think a bot is a player.

**Comment by VirxEC** [comment]
The way it works is that if it thinks you're a bot, it doesn't do anything. However, if it detects that you're a bot multiple times, then it kicks you from the server. I don't know if it ever bans you, but there's a command for an admin to do it. (/matix ban <player> <message>) And also it alerts all admins if a player is kicked for cheating.

**Comment by bokja** [comment]
A legit feature which slows down baritone overall would be really appreciated. The head flicks on #farm are insane and can easily be caught by anticheats.

**Comment by LoganDark** [comment]
> can easily be caught by anticheats.

Even vanilla catches that sometimes!

**Comment by 0-x-2-2** [comment]
> > can easily be caught by anticheats.
> 
> Even **_vanilla_** catches that sometimes!

sounds like fake news 🤔

**Comment by mrphax0r** [comment]
This should be pretty obvious as smooth head rotations are still not a thing.
"simulate player input to some point"

**Comment by 0-x-2-2** [comment]
yaas downvoted for a comment that is true. furry nation on top. vanilla anticheat == fly not enabled on this server.

**Comment by LoganDark** [comment]
@0-x-2-2 fly has nothing to do with turning your head, also what the hell is a furry nation

**Comment by 0-x-2-2** [comment]
u == furry

**Comment by 0-x-2-2** [comment]
lol, vanilla does NOT detect instantly turning your head.

**Comment by LoganDark** [comment]
dude, I'm not here to argue, sorry for offending you with my profile picture.

**Comment by 0-x-2-2** [comment]
I never said your profile picture offended me. 🤔🤔🤔🤔

**Comment by leijurv** [comment]
Fixed by https://github.com/cabaletta/baritone/commit/fa905b8844691e935db4cb06d0e29f10cba4f70c

**Comment by RandomName18** [comment]
@LoganDark Have you gotten to making the code for this yet? Im just curious

**Comment by LoganDark** [comment]
@RandomName18 I don't work on Baritone anymore.

**Comment by AlizerUncaged** [comment]
any news on this, I still get detected even if I have legitmine and free look enabled

**Comment by BigKake** [comment]
> any news on this, I still get detected even if I have legitmine and free look enabled

fugured out anything yet? thanks
